function [fitresult, gof] = piston_createFit(pressure, y_transform, a_init, b_init, k_init)
%CREATEFIT(PRESSURE,Y_TRANSFORM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: pressure
%      Y Output: y_transform
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Nov-2023 18:44:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pressure, y_transform );

% Set up fittype and options.
ft = fittype( 'log((x^(1/a)+b^(1/a))./(b^(1/a)))+k*x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [a_init b_init k_init];
opts.Lower = [1 0 0];
opts.Upper = [3 1000 0.01];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y_transform vs. pressure', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'pressure', 'Interpreter', 'none' );
% ylabel( 'y_transform', 'Interpreter', 'none' );
% grid on


