function [fitresult, gof] = piston_equ_por_createFit(pressure, porosity,init_porosity,init_a,init_b, init_k)
%CREATEFIT(ASCORBIC_ACID_PRESSURE,ASCORBIC_ACID_POR)
%  Create a fit.
%
%  Data for 'piston_equation_por' fit:
%      X Input: pressure
%      Y Output: porosity
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Nov-2023 19:06:39


%% Fit: 'piston_equation_por'.
scaled_porosity = porosity/init_porosity;
[xData, yData] = prepareCurveData( pressure, scaled_porosity );

% Set up fittype and options.
ft = fittype( '1./(((x^(1/a)+b^(1/a))./b^(1/a)).*exp(k*x))', 'independent', 'x', 'dependent', 'y','coefficients',{'a','b','k'} );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [init_a init_b init_k];
opts.Lower = [1 0 0];
opts.Upper = [3 1000 0.01];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


